name: minhaloja
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flavor_config: ^1.3.0
  dio: ^5.1.1
  pretty_dio_logger: ^1.2.0-beta-1
  logger: ^1.1.0
  localization: ^2.1.0
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.11.0
  flutter_svg: ^1.1.1+1
  carousel_slider: ^4.2.1
  flutter_pdfview: ^1.2.1
  polygon: ^0.1.0
  mask_text_input_formatter: ^2.4.0
  # jiffy: ^5.0.0
  either_dart: ^0.3.0
  permission_handler: ^10.2.0
  currency_text_input_formatter: ^2.1.8
  collection: ^1.16.0
  build_runner: ^2.3.0
  path_provider: ^2.0.14
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  fluttertoast: ^8.1.2
  uuid: ^3.0.7
  shimmer: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  shared_preferences: ^2.0.16
  flutter_secure_storage: ^7.0.1
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.2.6
  firebase_storage: ^11.4.1
  firebase_core: ^2.5.0
  mobile_scanner: ^3.2.0
  firebase_core_web: ^2.15.0
  firebase_auth_web: ^5.11.2
  firebase_storage_web: ^3.9.2
  cloud_firestore_web: ^3.12.0
  image_picker: ^1.0.4
  expandable_bottom_sheet: ^1.1.1+1
  url_launcher: ^6.1.10
  fl_chart: ^0.62.0
  flutter_login: ^4.2.1
  cached_network_image: ^3.3.1
  cached_network_image_web: ^1.1.1
  share_plus: ^9.0.0
  skeletonizer: ^1.1.1
  flutter_native_splash: ^2.2.14
  pluto_grid: ^8.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icon/
    - assets/icons/

  uses-material-design: true

flutter_native_splash:
  color: "#C65038"
  image: assets/images/splash.png

  web: true

